client_index:
    path:     /
    defaults: { _controller: "AdminBundle:DitClient:index" }
    methods:  GET

client_new:
    path:     /new
    defaults: { _controller: "AdminBundle:DitClient:new" }
    methods:  [GET, POST]

client_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:DitClient:edit" }
    methods:  [GET, POST]

client_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:DitClient:update" }
    methods:  [POST, PUT]

client_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:DitClient:delete" }
    methods:  [GET, DELETE]

client_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:DitClient:deleteGroup" }
    methods:  POST