facture_index:
    path:     /
    defaults: { _controller: "AdminBundle:DitFacture:index" }
    methods:  GET

facture_new:
    path:     /new
    defaults: { _controller: "AdminBundle:DitFacture:new" }
    methods:  [GET, POST]

facture_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:DitFacture:edit" }
    methods:  [GET, POST]

facture_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:DitFacture:update" }
    methods:  [POST, PUT]

facture_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:DitFacture:delete" }
    methods:  [GET, DELETE]

facture_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:DitFacture:deleteGroup" }
    methods:  POST

facture_detail:
    path:     /{id}/detail
    defaults: { _controller: "AdminBundle:DitFacture:detail" }
    methods:  GET

facture_update_paiement_payed:
    path:     /{id}/update-paiement-payed
    defaults: { _controller: "AdminBundle:DitFacture:updatePaiementPayed" }
    methods:  GET

facture_update_paiement_no_payed:
    path:     /{id}/update-paiement-no-payed
    defaults: { _controller: "AdminBundle:DitFacture:updatePaiementNoPayed" }
    methods:  GET

facture_update_status:
    path:     /{id}/update-status-{_status}
    defaults: { _controller: "AdminBundle:DitFacture:updateStatus" }
    methods:  GET