message_newsletter_index:
    path:     /
    defaults: { _controller: "AdminBundle:DitMessageNewsletter:index" }
    methods:  GET

message_newsletter_new:
    path:     /new
    defaults: { _controller: "AdminBundle:DitMessageNewsletter:new" }
    methods:  [GET, POST]

message_newsletter_send:
    path:     /{id}/send
    defaults: { _controller: "AdminBundle:DitMessageNewsletter:send" }
    methods:  [GET, POST]

message_newsletter_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:DitMessageNewsletter:edit" }
    methods:  [GET, POST]

message_newsletter_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:DitMessageNewsletter:update" }
    methods:  [POST, PUT]

message_newsletter_sendupdate:
    path:     /{id}/send-update
    defaults: { _controller: "AdminBundle:DitMessageNewsletter:sendUpdate" }
    methods:  [POST, PUT]

message_newsletter_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:DitMessageNewsletter:delete" }
    methods:  [ GET, DELETE ]

message_newsletter_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:DitMessageNewsletter:deleteGroup" }
    methods:  POST