service_index:
    path:     /
    defaults: { _controller: "AdminBundle:DitService:index" }
    methods:  GET

service_new:
    path:     /new
    defaults: { _controller: "AdminBundle:DitService:new" }
    methods:  [GET, POST]

service_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:DitService:edit" }
    methods:  [GET, POST]

service_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:DitService:update" }
    methods:  [POST, PUT]

service_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:DitService:delete" }
    methods:  [GET, DELETE]

service_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:DitService:deleteGroup" }
    methods:  POST