service_client_list_ajax:
    path:     /list-ajax-{_type}
    defaults: { _controller: "AdminBundle:DitServiceClient:listAjax" }
    methods:  GET

service_client_list_not_validated:
    path:     /
    defaults: { _controller: "AdminBundle:DitServiceClient:listNotValidated" }
    methods:  GET

service_client_list_validated:
    path:     /validated
    defaults: { _controller: "AdminBundle:DitServiceClient:listValidated" }
    methods:  GET

service_client_list:
    path:     /list
    defaults: { _controller: "AdminBundle:DitServiceClient:list" }
    methods:  GET

service_client_new:
    path:     /new
    defaults: { _controller: "AdminBundle:DitServiceClient:new" }
    methods:  [GET, POST]

service_client_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:DitServiceClient:edit" }
    methods:  [GET, POST]

service_client_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:DitServiceClient:update" }
    methods:  [POST, PUT]

service_client_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:DitServiceClient:delete" }
    methods:  [GET, DELETE]

service_client_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:DitServiceClient:deleteGroup" }
    methods:  POST

service_client_detail:
    path:     /detail/{id}
    defaults: { _controller: "AdminBundle:DitServiceClient:detail" }
    methods:  GET

service_client_update_status_validation_ajax:
    path:     /update-status-validation-ajax
    defaults: { _controller: "AdminBundle:DitServiceClient:updateStatusValidationAjax" }
    methods:  POST

service_client_cancel_status_validation_ajax:
    path:     /cancel-status-validation-ajax
    defaults: { _controller: "AdminBundle:DitServiceClient:cancelStatusValidationAjax" }
    methods:  POST

service_client_update_status_project_ajax:
    path:     /update-status-project-ajax
    defaults: { _controller: "AdminBundle:DitServiceClient:updateStatusProjectAjax" }
    methods:  POST

service_client_list_service_option_ajax:
    path:     /list-service-option-ajax
    defaults: { _controller: "AdminBundle:DitServiceClient:listServiceOptionAjax" }
    methods:  POST

service_client_prix_commande_ajax:
    path:     /prix-commande-ajax
    defaults: { _controller: "AdminBundle:DitServiceClient:prixCommandeAjax" }
    methods:  POST

service_client_send_email_connexion_ajax:
    path:     /send-email-connexion-ajax
    defaults: { _controller: "AdminBundle:DitServiceClient:sendEmailConnexionClientAjax" }
    methods:  POST

service_client_finalise_status_validation_ajax:
    path:     /finalise-status-validation-ajax
    defaults: { _controller: "AdminBundle:DitServiceClient:finaliseStatusValidationAjax" }
    methods:  POST

service_client_lien_livre_status_validation_ajax:
    path:     /lien-livre-status-validation-ajax
    defaults: { _controller: "AdminBundle:DitServiceClient:lienLivreStatusValidationAjax" }
    methods:  POST

service_client_send_email_confirmation_paiement_ajax:
    path:     /send-email-confirmation-paiement-ajax
    defaults: { _controller: "AdminBundle:DitServiceClient:sendEmailConfirmationPaiementAjax" }
    methods:  POST

service_client_delete_file_ajax:
    path:     /delete-file
    defaults: { _controller: "AdminBundle:DitServiceClient:deleteFileAjax" }
    methods:  POST