service_type_index:
    path:     /
    defaults: { _controller: "AdminBundle:DitServiceType:index" }
    methods:  GET

service_type_new:
    path:     /new
    defaults: { _controller: "AdminBundle:DitServiceType:new" }
    methods:  [GET, POST]

service_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:DitServiceType:edit" }
    methods:  [GET, POST]

service_type_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:DitServiceType:update" }
    methods:  [POST, PUT]

service_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:DitServiceType:delete" }
    methods:  [GET, DELETE]

service_type_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:DitServiceType:deleteGroup" }
    methods:  POST