service_option_type_index:
    path:     /
    defaults: { _controller: "AdminBundle:DitServiceOptionType:index" }
    methods:  GET

service_option_type_new:
    path:     /new
    defaults: { _controller: "AdminBundle:DitServiceOptionType:new" }
    methods:  [GET, POST]

service_option_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:DitServiceOptionType:edit" }
    methods:  [GET, POST]

service_option_type_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:DitServiceOptionType:update" }
    methods:  [POST, PUT]

service_option_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:DitServiceOptionType:delete" }
    methods:  [GET, DELETE]

service_option_type_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:DitServiceOptionType:deleteGroup" }
    methods:  POST