slide_index:
    path:     /
    defaults: { _controller: "AdminBundle:DitSlide:index" }
    methods:  GET

slide_new:
    path:     /new
    defaults: { _controller: "AdminBundle:DitSlide:new" }
    methods:  [GET, POST]

slide_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:DitSlide:edit" }
    methods:  [GET, POST]

slide_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:DitSlide:update" }
    methods:  [POST, PUT]

slide_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:DitSlide:delete" }
    methods:  [GET, DELETE]

slide_delete_group:
    path:     /delete-group
    defaults: { _controller: "AdminBundle:DitSlide:deleteGroup" }
    methods:  POST