dit_user:
    resource: "@UserBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user

dit_login:
    path: /login
    defaults: { _controller: UserBundle:Security:login }

dit_resetting_password:
    path: /{_locale}/resetting-password
    defaults: { _controller: "UserBundle:User:resettingPassword", _locale : fr }
    methods: [GET, POST]
    requirements:
        _locale: en|fr
